---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-deployment
  namespace: flux-system
spec:
  dependsOn:
    - name: capacitor
  interval: 1h
  wait: true
  prune: true
  timeout: 10m
  sourceRef:
    kind: OCIRepository
    name: capacitor
  path: ./
  targetNamespace: capacitor