---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ic-ingress-stack
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/Infra-Coders/ic-ingress-stack.git
  ref:
    branch: wm-proper-approach
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ic-ingress-stack
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: ic-ingress-stack
  prune: true
