apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ic-ingress-stack
  namespace: flux-system
spec:
  url: https://github.com/Infra-Coders/ic-ingress-stack.git
  ref:
    tag: v0.0.1
  interval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ic-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: ic-aws
  sourceRef:
    kind: GitRepository
    name: ic-ingress-stack
  path: ./clusters/dev
  prune: true
  interval: 2m
